#' link_delaunay
#'
#' Calculate links between boundary cells across masked regions in the layers of
#' a geoglist using Delaunay triangulation. Links can be discarded if they fall
#' above a threshold distance.
#'
#' @param geog `geoglist`. The output of `rast_to_geoglist()`.
#' @param max.dist `numeric` or `NULL`. If not `NULL`, then the maximum link
#' length permitted in metres. Only links below this threshold will be returned.
#' @param verbose `logical`. Should function progress be to the user? This may
#' be useful when dealing with large rasters (high resolution and/or many layers).
#' @return A `geoglist` as supplied in `geog` with the additional element, `links`.
#' This contains an `sf data.frame` of linestrings representing the island links,
#' recording their start and end cell IDs, the landscape layer to which they belong
#' and their lengths in metres. If links were already generated using another
#' function from TARDIS, they are appended to the existing element `links` and
#' duplicate entries removed. If no landscape layers contained islands, then
#' `geog` is returned without this additional slot.
#' @import terra sf h3jsr
#' @export
#'
#' @details
#' Like masking, linkage is another key feature of TARDIS. We may still want to
#' permit movement between cells at the edges of unmasked regions across intervening
#' masked space. Delaunay triangulation is used to calculate line-of-site linkage
#' between these boundary cells. Links which intersect unmasked regions other than
#' at their start and end points are discarded.
#'
#' The result of this procedure is denser network of linkages compared to those
#' generated by `TARDIS::link_mask()`, where single links are generated between
#' neighbouring islands. As Delaunay linkage is only based on line-of-site,
#' it is possible for links to connect between cells on the same island. This
#' may be desirable, however, where shorter distances across masked space may
#' be more reasonable compared to much longer routes that remain in unmasked space.
#'
#' Currently, links are calculated using `terra::delaunay()`. While terra generally
#' uses spherical geometry, this function appears to be a rare exception where
#' spherical geometry is not yet supported. As such, Delaunay linkage on global
#' scales is approximate, although it still appears to return reasonable results.
#'
#' @examples
#' \dontrun{
#' library(terra)
#' library(TARDIS)
#'
#' # load a dataset of the Galapagos archipelago through geological time
#' gal <- TARDIS::galapagos()
#' gal <- crop(gal, ext(-92, -88, -2, 1))
#'
#' # create a land-sea mask from the archipelago raster set
#' gal_m <- classify(gal, matrix(c(-Inf, 0, NA, 0, Inf, 1), ncol = 3, byrow = T), right = F)
#'
#' # create a geoglist with hexagonal resampling and mask the sea
#' hexes <- rast_to_geoglist(gal, gal_m, as.hex = T, hex = 6)
#' hexes <- link_delaunay(hexes)
#'
#' # create a geoglist in raster format and mask the sea
#' rasts <- rast_to_geoglist(gal, gal_m)
#' rasts <- link_delaunay(rasts)
#'
#' # plot the first layer of the geoglist and add the island links
#' layer_ind = 1
#' plot(rasts$layers[[layer_ind]])
#' plot(rasts$links[[layer_ind]]]$geometry[which(rasts$links$bin == layer_ind)], add = T)
#'
#' plot(hexes$layers[[layer_ind]]$geometry)
#' plot(hexes$links[[layer_ind]]]$geometry[which(hexes$links$bin == layer_ind)], add = T)
#' }

link_delaunay <- function(geog, max.dist = NULL, verbose = T) {
  #
  # geog = foo2
  # max.dist = NULL
  # verbose = T
  #
  if(!exists("geog")) {
    stop("Supply geog as a geoglist from rast_to_geoglist()")
  }
  if(!inherits(geog, "geoglist")) {
    stop("Supply geog as a geoglist from rast_to_geoglist()")
  }
  if(!is.null(max.dist)) {
    if (length(max.dist) != 1 | !inherits(max.dist, "numeric")) {
      stop("If not NULL, max.dist should be a numeric distance in metres")
    }
    if (!max.dist%%1 == 0) {
      stop("If not NULL, max.dist should be a numeric distance in metres")
    }
  }
  if(!is.logical(verbose) | length(verbose) != 1) {
    stop("verbose should be logical")
  }

  if(inherits(geog$layers, "SpatRaster")) {

    islands <- rast(lapply(geog$layers, patches, directions = 8, allowGaps = F))
    bounds <- lapply(1:nlyr(islands), function(x) {
      pt <- as.points(mask(islands[[x]], classify(boundaries(islands[[x]]), cbind(0, NA))))
      aggregate(pt, by = "patches")
    })

  } else {

    grid <- get_grid(geog$gdat[1:4], geog$gdat[7])
    dat <- lapply(geog$layers, function(z) {
      bar <- relate(z, z, "intersects", pairs = T)
      z$patches <- components(graph_from_edgelist(bar))$membership
      z2 <- centroids(z[which(table(bar[,1]) != 7)])
      list(z, aggregate(z2, by = "patches"))
    })
    islands <- lapply(dat, `[[`, 1)
    bounds <- lapply(dat, `[[`, 2)
  }

  res_list <- list()
  for (i in 1:length(bounds)) {

    if (verbose) {
      cat(paste0("Resolving layers [", i, "/", length(bounds), "]\r"))
      if (i == length(bounds)) {cat("\n")}
    }

    if(!all(bounds[[i]]$patches == 1)) {

      pts <- bounds[[i]]
      dl <- delaunay(pts)
      dl <- disagg(as.lines(dl), segments = T)

      if(inherits(geog$layers, "SpatRaster")) {
        nr <- extract(islands[[i]], dl)
        nr <- subset(nr, complete.cases(nr))
        to_keep <- which(tapply(nr$patches, nr$ID, length) == 2)
        dl <- dl[to_keep]
        nr <- matrix(cellFromXY(geog$layers[[1]], geom(dl)[,3:4]), ncol = 2,  byrow = T)
        to_keep <- which(!abs(nr[,1] - nr[,2]) %in% c(1, geog$gdat[6], geog$gdat[6] + 1, geog$gdat[6] - 1))
        dl <- dl[to_keep]
        cl <- cellFromXY(geog$layers[[1]], geom(dl)[,3:4])
        cls <- as.data.frame(matrix(cl, ncol = 2, byrow = T))

      } else {

        nr <- apply(relate(dl, islands[[i]], "intersects"), 1, which)
        to_keep <- which(sapply(nr, length) == 2)
        nr <- nr[to_keep]
        #nr <- lapply(nr, function(x) {islands[[i]]$patches[x]})
        #nr <- which(sapply(nr, function(x) {x[1] != x[2]}))
        nr <- which(!sapply(nr, function(x) {is.related(islands[[i]][x[1]], islands[[i]][x[2]], "touches")}))
        dl <- dl[to_keep[nr]]
        cl <- suppressMessages(point_to_cell(geom(dl)[,3:4], res = geog$gdat[7]))
        cl <- match(cl, grid)
        cls <- as.data.frame(matrix(cl, ncol = 2, byrow = T))
      }

      colnames(cls) <- c("srt", "end")
      cls$layer <- i
      cls$distance <- perim(dl)
      st_geometry(cls) <- st_as_sf(dl)$geometry
      if(!is.null(max.dist)) {
        cls <- cls[which(cls$distance <= max.dist),]
      }
      res_list[[i]] <- cls
    }
  }
  if(all(sapply(res_list, is.null))) {
    message("No islands found in any layers, no links will be returned")
    return(NULL)
  } else {
    lnks <- st_wrap_dateline(do.call(rbind, res_list), options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"))
    if(!is.null(geog$links)) {
      geog$links <- unique(rbind(geog$links, vect(lnks)))
    } else {
      geog$links <- vect(lnks)
    }
    return(geog)
  }
}
